config/routes.rb
Rails.application.routes.draw do
  
  get 'products/create'

  get 'products/update'

  get 'products/index'

  get 'products/destroy'

  get 'events/new'

  get 'events/edit'

  get 'demo/home'

  get 'demo/products'

  get 'demo/start_money'

  get 'demo/end_money'

  get 'demo/selling'

  get 'demo/event_saved'

  root 'artists#new'
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :products
  resources :events
  resources :line_items
  resources :users

  resources :artists do
    resources :events
    resources :products
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def home
  end

  def products
  end

  def start_money
  end

  def end_money
  end

  def selling
  end

  def event_saved
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/demo/end_money.html.erb
<div class="w-section">
    <div class="w-container header"><%= link_to "Save >", demo_event_saved_url, class: "w-button right-header-button" %>
      <h4 class="header-title">Depot Leuven - End Money</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      <div class="instruction-text">What a sales talent! Before you close the shop, you might count the money in the cash register again.</div>
      <h1 class="content-title">Total: € 0</h1>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-11">€ 100</label>
          <input class="w-input rounded-text-field inline" id="name-11" type="text" name="name-11" data-name="Name 11">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-12">€ 50</label>
          <input class="w-input rounded-text-field inline" id="name-12" type="text" name="name-12" data-name="Name 12">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-13">€ 20</label>
          <input class="w-input rounded-text-field inline" id="name-13" type="text" name="name-13" data-name="Name 13">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-14">€ 10</label>
          <input class="w-input rounded-text-field inline" id="name-14" type="text" name="name-14" data-name="Name 14">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-15">€ 5</label>
          <input class="w-input rounded-text-field inline" id="name-15" type="text" name="name-15" data-name="Name 15">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-16">€ 2</label>
          <input class="w-input rounded-text-field inline" id="name-16" type="text" name="name-16" data-name="Name 16">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-17">€ 1</label>
          <input class="w-input rounded-text-field inline" id="name-17" type="text" name="name-17" data-name="Name 17">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-18">€ 0,50</label>
          <input class="w-input rounded-text-field inline" id="name-18" type="text" name="name-18" data-name="Name 18">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-19">€ 0,20</label>
          <input class="w-input rounded-text-field inline" id="name-19" type="text" name="name-19" data-name="Name 19">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-20">€ 0,10</label>
          <input class="w-input rounded-text-field inline" id="name-20" type="text" name="name-20" data-name="Name 20">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
    </div>
  </div>

app/views/demo/event_saved.html.erb
<div class="w-section">
    <div class="w-container header">
      <h4 class="header-title">Depot Leuven - saved</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      <div class="instruction-text">Congratulations! You earned € 480 today.
        <br>
        <br>You probably don't want to lose your data.
        <br>Register for an account.</div>
      <div class="w-form centered-form">
        <form id="email-form" name="email-form" data-name="Email Form" data-redirect="/products">
          <input class="w-input rounded-text-field" id="email" type="email" placeholder="your email address" name="email" data-name="email">
          <input class="w-input rounded-text-field" id="password" type="password" placeholder="choose a password" name="password" data-name="password">
          <input class="w-button centered-button" type="submit" value="Sign up" data-wait="Please wait...">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
    </div>
  </div>

app/views/demo/home.html.erb
<div class="w-section">
    <div class="w-container header"><a class="w-button right-header-button" href="#">Log in</a>
      <h4 class="header-title">MerchCount</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      
      <h1 class="h1-centered">Keep your merch stand organized</h1>
      <h2 class="h2-centered">Keep track of your merch sales, products and cashflow.</h2>
      
      <%= image_tag("merchcount_logo.png", class: "home-logo") %>
      
      <div class="w-form centered-form">
        <form id="email-form" name="email-form" data-name="Email Form">
          <input class="w-input rounded-text-field" id="artist-name" type="text" placeholder="Artist name" name="artist-name" data-name="artist name">
          <input class="w-input rounded-text-field" id="venue" type="text" placeholder="What's the venue for tonight?" name="venue" data-name="venue">         
        </form>
        <%= link_to "Let's get started", demo_products_url, class: "w-button centered-button" %>
        </div>
      </div>
    </div>
  </div>

app/views/demo/products.html.erb
<div class="w-section">
    <div class="w-container header"><%= link_to "Next >", demo_start_money_url, class: "w-button right-header-button" %>
      <h4 class="header-title">Kenji Minogue - Products</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      <div class="instruction-text">Kenji Minogue put on a great show. Time to sell some merchandise.
        <br>First let's list the products that you sell. CDs, t-shirts, etc.</div>
      <div class="w-form centered-form">
        <form id="email-form" name="email-form" data-name="Email Form">
          <div class="w-row">
            <div class="w-col w-col-6 w-col-small-6">
              <input class="w-input rounded-text-field" id="product-name" type="text" placeholder="product name, e.g. CD" name="product-name" data-name="product name">
            </div>
            <div class="w-col w-col-6 w-col-small-6">
              <input class="w-input rounded-text-field" id="price" type="text" placeholder="price" name="price" data-name="price">
            </div>
          </div>
          <input class="w-button centered-button" type="submit" value="Create New Product" data-wait="Please wait...">
        </form>
      </div>
      <ul class="w-list-unstyled iphone-list">
        <li class="w-clearfix iphone-list-item first-child">
          <div class="price-tag">€ 20</div>
          <div>vinyl</div>
        </li>
        <li class="w-clearfix iphone-list-item">
          <div class="price-tag">€ 15</div>
          <div>CD</div>
        </li>
        <li class="w-clearfix iphone-list-item last-child">
          <div class="price-tag">€ 20</div>
          <div>t-shirt</div>
        </li>
      </ul>
    </div>
  </div>

app/views/demo/selling.html.erb
<div class="w-section">
    <div class="w-container header"><%= link_to "Next >", demo_end_money_url, class: "w-button right-header-button" %>
      <h4 class="header-title">Depot Leuven - Selling</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      <div class="instruction-text">You're ready to roll. Let the customers come!</div>
      <ul class="w-list-unstyled iphone-list">
        <li class="w-clearfix iphone-list-item first-child">
          <div class="count-block">
          	<%= image_tag "minus_button.png", class: "count-button" %>
          	<%= image_tag "plus_button.png", class: "count-button" %>
            <div class="count-bubble">0</div>
          </div>
          <div>vinyl</div>
        </li>
        <li class="w-clearfix iphone-list-item">
          <div class="count-block">
          	<%= image_tag "minus_button.png", class: "count-button" %>
          	<%= image_tag "plus_button.png", class: "count-button" %>
            <div class="count-bubble">0</div>
          </div>
          <div>CD</div>
        </li>
        <li class="w-clearfix iphone-list-item last-child">
          <div class="count-block">
          	<%= image_tag "minus_button.png", class: "count-button" %>
          	<%= image_tag "plus_button.png", class: "count-button" %>
            <div class="count-bubble">0</div>
          </div>
          <div>t-shirt</div>
        </li>
      </ul>
    </div>
  </div>

app/views/demo/start_money.html.erb
<div class="w-section">
    <div class="w-container header"><%= link_to "Next >", demo_selling_url, class: "w-button right-header-button" %>
      <h4 class="header-title">Depot Leuven - Start Money</h4>
    </div>
  </div>
  <div class="w-section">
    <div class="w-container red-background">
      <div class="instruction-text">Awesome, you have some nice merch items over here.
        <br>Now it might be a good idea to count the money in your cash register.</div>
      <h1 class="content-title">Total: € 0</h1>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name">€ 100</label>
          <input class="w-input rounded-text-field inline" id="name" type="text" name="name" data-name="Name">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-2">€ 50</label>
          <input class="w-input rounded-text-field inline" id="name-2" type="text" name="name-2" data-name="Name 2">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-4">€ 20</label>
          <input class="w-input rounded-text-field inline" id="name-4" type="text" name="name-4" data-name="Name 4">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-3">€ 10</label>
          <input class="w-input rounded-text-field inline" id="name-3" type="text" name="name-3" data-name="Name 3">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-10">€ 5</label>
          <input class="w-input rounded-text-field inline" id="name-10" type="text" name="name-10" data-name="Name 10">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-9">€ 2</label>
          <input class="w-input rounded-text-field inline" id="name-9" type="text" name="name-9" data-name="Name 9">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-8">€ 1</label>
          <input class="w-input rounded-text-field inline" id="name-8" type="text" name="name-8" data-name="Name 8">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-7">€ 0,50</label>
          <input class="w-input rounded-text-field inline" id="name-7" type="text" name="name-7" data-name="Name 7">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-6">€ 0,20</label>
          <input class="w-input rounded-text-field inline" id="name-6" type="text" name="name-6" data-name="Name 6">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
      <div class="w-form centered-form moneycount">
        <form id="email-form" name="email-form" data-name="Email Form">
          <label class="inline-form-label" for="name-5">€ 0,10</label>
          <input class="w-input rounded-text-field inline" id="name-5" type="text" name="name-5" data-name="Name 5">
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
    </div>
  </div>